# Use postgres/example user/password credentials
version: '3.1'

services:
  postgresql-db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
